import pool from '../config/db.js';

async function main() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    console.log('Dropping identity if exists...');
    try {
      await client.query('ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP IDENTITY IF EXISTS');
    } catch (e) {
      console.warn('DROP IDENTITY error (ignored):', (e as Error).message);
    }

    console.log('Dropping default if any...');
    try {
      await client.query('ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP DEFAULT');
    } catch (e) {
      console.warn('DROP DEFAULT error (ignored):', (e as Error).message);
    }

    console.log('Listing owned sequences...');
    const q = `
      SELECT n.nspname AS schemaname, s.relname AS seqname
      FROM pg_class s
      JOIN pg_namespace n ON n.oid = s.relnamespace
      JOIN pg_depend d ON d.objid = s.oid
      JOIN pg_class t ON t.oid = d.refobjid
      JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
      WHERE s.relkind = 'S'
        AND t.relname = 'api_bil_claim_reimburse'
        AND a.attname = 'bil_claim_reimburse_id'
    `;
    const res = await client.query(q);
    console.log('Found sequences:', res.rowCount);
    for (const r of res.rows) {
      const fq = `${r.schemaname}.${r.seqname}`;
      console.log('Detaching and dropping sequence', fq);
      try {
        await client.query(`ALTER SEQUENCE ${fq} OWNED BY NONE`);
      } catch (e) {
        console.warn('OWNED BY NONE error (ignored):', (e as Error).message);
      }
      try {
        await client.query(`DROP SEQUENCE IF EXISTS ${fq}`);
      } catch (e) {
        console.warn('DROP SEQUENCE error (ignored):', (e as Error).message);
      }
    }

    console.log('Re-adding identity...');
    await client.query('ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id ADD GENERATED BY DEFAULT AS IDENTITY');

    await client.query('COMMIT');
    console.log('Repair complete');
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
}

main().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
