-- Migration: 005_create_rcm_file_uploads_audit.sql
-- Purpose: Create an audit table to track metadata for all file uploads (Excel/PDF/CSV) in the RCM system.
-- Notes:
--  - Tracks only file metadata (no claim data).
--  - Each upload has a UUID upload_id and a sequential upload_seq starting at 1 for human readability.
--  - Stores file type, clinic, uploader, storage location (S3), hash for idempotency, row/page counts, and processing status.

-- Enable UUID generation if not already enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Optional generic touch function (idempotent); shared by multiple tables
CREATE OR REPLACE FUNCTION trg_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;$$ LANGUAGE plpgsql;

-- Create uploads audit table
CREATE TABLE IF NOT EXISTS rcm_file_uploads (
  upload_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  upload_seq        BIGINT GENERATED BY DEFAULT AS IDENTITY, -- starts at 1 and increments

  -- Core classification
  file_kind         text NOT NULL CHECK (
                      file_kind IN ('SUBMIT_EXCEL','REIMBURSE_PDF','REIMBURSE_EXCEL','OA_STATUS_CSV')
                    ),
  clinic            text,

  -- File identity & storage
  original_filename text NOT NULL,
  mime_type         text,
  original_filesize_bytes BIGINT,
  s3_url            text NOT NULL,
  s3_bucket         text,
  s3_key            text,
  storage_provider  text NOT NULL DEFAULT 's3' CHECK (storage_provider IN ('s3','local','azure_blob','gcs')),
  content_sha256    text NOT NULL,

  -- Parsing/processing metrics
  row_count         integer,     -- rows parsed (Excel/CSV)
  page_count        integer,     -- pages parsed (PDF)

  -- Processing lifecycle
  status            text NOT NULL DEFAULT 'COMPLETED' CHECK (
                      status IN ('PENDING','COMPLETED','FAILED','ROLLED_BACK')
                    ),
  message           text,             -- error/warning message if any
  processing_started_at   timestamptz,
  processing_completed_at timestamptz,

  -- Audit
  created_by        text,             -- uploader identifier (user/email)
  created_by_user_id integer REFERENCES rcm_portal_auth_users(id) ON DELETE SET NULL,
  created_from_ip   text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
  -- end of columns
);

-- Ensure upload_seq is unique and indexed for quick lookup/display
CREATE UNIQUE INDEX IF NOT EXISTS uq_rcm_file_uploads_upload_seq ON rcm_file_uploads(upload_seq);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_rcm_file_uploads_created_at ON rcm_file_uploads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rcm_file_uploads_status ON rcm_file_uploads(status);
CREATE INDEX IF NOT EXISTS idx_rcm_file_uploads_kind_created ON rcm_file_uploads(file_kind, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rcm_file_uploads_content_sha256 ON rcm_file_uploads(content_sha256);
CREATE INDEX IF NOT EXISTS idx_rcm_file_uploads_created_by_user_id ON rcm_file_uploads(created_by_user_id);

-- Uniqueness guard (best-effort): prevent exact same content re-upload per clinic & kind
-- Using a unique index on expression since constraints can't include expressions
CREATE UNIQUE INDEX IF NOT EXISTS uq_rcm_file_uploads_dedup
  ON rcm_file_uploads (file_kind, (COALESCE(clinic, '')), content_sha256);

-- Touch trigger for updated_at
DROP TRIGGER IF EXISTS trg_touch_rcm_file_uploads ON rcm_file_uploads;
CREATE TRIGGER trg_touch_rcm_file_uploads
BEFORE UPDATE ON rcm_file_uploads
FOR EACH ROW EXECUTE FUNCTION trg_touch_updated_at();

-- Back-compat view exposing the minimal requested schema name `uploads`
CREATE OR REPLACE VIEW uploads AS
SELECT
  upload_id,
  file_kind,
  clinic,
  original_filename,
  s3_url,
  content_sha256,
  row_count,
  status,
  message,
  created_by,
  created_at
FROM rcm_file_uploads;

-- Commentary:
-- The request mentioned "let the uuid start with 1,2,3 and move forward" — UUIDs are not sequential.
-- To satisfy sequential identifiers, this migration adds upload_seq (identity) starting at 1 while keeping upload_id (UUID) as the stable unique identifier.
-- Table name preference "RCM_File uploads" is implemented as snake_case rcm_file_uploads to comply with PostgreSQL naming rules.
