-- Migration: 007_add_reimburse_system_columns.sql
-- Purpose: Add linkage/system columns to api_bil_claim_reimburse, set PK if missing, add FKs, uniqueness, and indexes.

-- 1) Add linkage + system columns (idempotent)
ALTER TABLE api_bil_claim_reimburse
  ADD COLUMN IF NOT EXISTS bil_claim_reimburse_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS bil_claim_submit_id   BIGINT,
  ADD COLUMN IF NOT EXISTS upload_id             UUID,
  ADD COLUMN IF NOT EXISTS s3_pdf_url            TEXT,
  ADD COLUMN IF NOT EXISTS ocr_status            TEXT DEFAULT 'PENDING'
      CHECK (ocr_status IN ('PENDING','PARSED','FAILED')),
  ADD COLUMN IF NOT EXISTS ocr_log               TEXT,
  ADD COLUMN IF NOT EXISTS created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at            TIMESTAMPTZ NOT NULL DEFAULT now();

-- 2) Primary key (only if none exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'api_bil_claim_reimburse'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE api_bil_claim_reimburse
      ADD CONSTRAINT pk_api_bil_claim_reimburse
      PRIMARY KEY (bil_claim_reimburse_id);
  END IF;
END$$;

-- 3) Foreign keys (idempotent via name checks)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_reimburse_submit'
  ) THEN
    ALTER TABLE api_bil_claim_reimburse
      ADD CONSTRAINT fk_reimburse_submit
        FOREIGN KEY (bil_claim_submit_id)
        REFERENCES api_bil_claim_submit(bil_claim_submit_id)
        ON DELETE CASCADE;
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_reimburse_upload'
  ) THEN
    ALTER TABLE api_bil_claim_reimburse
      ADD CONSTRAINT fk_reimburse_upload
        FOREIGN KEY (upload_id)
        REFERENCES rcm_file_uploads(upload_id);
  END IF;
END$$;

-- 4) Uniqueness: one reimburse record per claim per cycle (if cycle used), else single record per claim
DO $$
DECLARE
  has_cycle_column BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='api_bil_claim_reimburse'
      AND column_name='reimbursement_cycle_date'
  ) INTO has_cycle_column;

  IF has_cycle_column THEN
    IF to_regclass('public.uq_reimburse_claim_cycle') IS NULL THEN
      EXECUTE $sql$CREATE UNIQUE INDEX uq_reimburse_claim_cycle
        ON api_bil_claim_reimburse (
          bil_claim_submit_id,
          COALESCE(reimbursement_cycle_date, DATE '1900-01-01')
        )$sql$;
    END IF;
  ELSE
    IF to_regclass('public.uq_reimburse_claim') IS NULL THEN
      EXECUTE 'CREATE UNIQUE INDEX uq_reimburse_claim ON api_bil_claim_reimburse (bil_claim_submit_id)';
    END IF;
  END IF;
END$$;

-- 5) Helpful indexes for UI
CREATE INDEX IF NOT EXISTS idx_reimburse_submit_id   ON api_bil_claim_reimburse(bil_claim_submit_id);
CREATE INDEX IF NOT EXISTS idx_reimburse_status      ON api_bil_claim_reimburse(claim_status);
CREATE INDEX IF NOT EXISTS idx_reimburse_payerstat   ON api_bil_claim_reimburse(prim_status);
CREATE INDEX IF NOT EXISTS idx_reimburse_upload      ON api_bil_claim_reimburse(upload_id);

-- Touch trigger for updated_at (uses shared function if present)
CREATE OR REPLACE FUNCTION trg_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_api_bil_claim_reimburse ON api_bil_claim_reimburse;
CREATE TRIGGER trg_touch_api_bil_claim_reimburse
BEFORE UPDATE ON api_bil_claim_reimburse
FOR EACH ROW EXECUTE FUNCTION trg_touch_updated_at();
