-- Migration: 010_fix_reimburse_id_sequence.sql
-- Purpose: Resolve "more than one owned sequence found" on api_bil_claim_reimburse.bil_claim_reimburse_id
-- by removing duplicate owned sequences/defaults and re-adding a single identity.

-- Drop identity/default only if present
DO $$
DECLARE
  is_identity boolean;
BEGIN
  SELECT EXISTS (
      SELECT 1
      FROM information_schema.columns c
      WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse'
        AND c.column_name='bil_claim_reimburse_id'
        AND c.is_identity='YES'
    ) INTO is_identity;

  IF is_identity THEN
    BEGIN
      EXECUTE 'ALTER TABLE api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP IDENTITY IF EXISTS';
    EXCEPTION WHEN others THEN
      -- ignore
    END;
  END IF;

  -- Drop DEFAULT if any lingering default exists
  BEGIN
    IF (SELECT column_default IS NOT NULL FROM information_schema.columns c WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse' AND c.column_name='bil_claim_reimburse_id' LIMIT 1) THEN
      EXECUTE 'ALTER TABLE api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP DEFAULT';
    END IF;
  EXCEPTION WHEN others THEN
    -- ignore
  END;
END$$;

-- Detach and drop any sequences owned by the column (identity or serial leftovers)
DO $$
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN
    SELECT nsp.nspname AS seq_schema, seq.relname AS seq_name
    FROM pg_class seq
    JOIN pg_namespace nsp ON nsp.oid = seq.relnamespace
    JOIN pg_depend d ON d.objid = seq.oid
    JOIN pg_class tbl ON d.refobjid = tbl.oid
    JOIN pg_attribute att ON d.refobjid = att.attrelid AND d.refobjsubid = att.attnum
    WHERE seq.relkind = 'S'
      AND d.deptype IN ('a','n')  -- auto/normal owned dependency
      AND tbl.relname = 'api_bil_claim_reimburse'
      AND att.attname = 'bil_claim_reimburse_id'
  LOOP
    BEGIN
      EXECUTE format('ALTER SEQUENCE %I.%I OWNED BY NONE', rec.seq_schema, rec.seq_name);
    EXCEPTION WHEN others THEN
      -- ignore
    END;
    BEGIN
      EXECUTE format('DROP SEQUENCE IF EXISTS %I.%I CASCADE', rec.seq_schema, rec.seq_name);
    EXCEPTION WHEN others THEN
      -- ignore
    END;
  END LOOP;
END$$;

-- Re-add a clean identity sequence
DO $$
DECLARE
  is_identity boolean;
BEGIN
  SELECT EXISTS (
      SELECT 1
      FROM information_schema.columns c
      WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse'
        AND c.column_name='bil_claim_reimburse_id'
        AND c.is_identity='YES'
    ) INTO is_identity;
  IF NOT is_identity THEN
    EXECUTE 'ALTER TABLE api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END$$;

-- Ensure primary key exists on the identity column
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'api_bil_claim_reimburse'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE api_bil_claim_reimburse
      ADD CONSTRAINT pk_api_bil_claim_reimburse PRIMARY KEY (bil_claim_reimburse_id);
  END IF;
END$$;
