-- Clean up duplicate sequences owned by api_bil_claim_reimburse.bil_claim_reimburse_id
-- Idempotent: drops identity/default if present, detaches and drops any owned sequences, then re-adds identity

DO $$
DECLARE
  is_identity boolean;
  r RECORD;
BEGIN
  -- Drop identity if present
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns c
    WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse'
      AND c.column_name='bil_claim_reimburse_id' AND c.is_identity='YES'
  ) INTO is_identity;

  IF is_identity THEN
    BEGIN
      EXECUTE 'ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP IDENTITY IF EXISTS';
    EXCEPTION WHEN others THEN
      -- ignore
    END;
  END IF;

  -- Drop default if any
  BEGIN
    IF (
      SELECT column_default IS NOT NULL FROM information_schema.columns c
      WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse'
        AND c.column_name='bil_claim_reimburse_id' LIMIT 1
    ) THEN
      EXECUTE 'ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id DROP DEFAULT';
    END IF;
  EXCEPTION WHEN others THEN
    -- ignore
  END;

  -- Detach and drop any sequences owned by this column
  FOR r IN (
    SELECT n.nspname AS schemaname, s.relname AS seqname
    FROM pg_class s
    JOIN pg_namespace n ON n.oid = s.relnamespace
    JOIN pg_depend d ON d.objid = s.oid AND d.deptype IN ('a','i')
    JOIN pg_class t ON t.oid = d.refobjid
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
    WHERE s.relkind = 'S'
      AND n.nspname = 'public'
      AND t.relname = 'api_bil_claim_reimburse'
      AND a.attname = 'bil_claim_reimburse_id'
  ) LOOP
    BEGIN
      EXECUTE format('ALTER SEQUENCE %I.%I OWNED BY NONE', r.schemaname, r.seqname);
    EXCEPTION WHEN others THEN
      -- ignore
    END;
    BEGIN
      EXECUTE format('DROP SEQUENCE IF EXISTS %I.%I', r.schemaname, r.seqname);
    EXCEPTION WHEN others THEN
      -- ignore
    END;
  END LOOP;
END $$;

-- Re-add identity cleanly if not present
DO $$
DECLARE
  is_identity boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns c
    WHERE c.table_schema='public' AND c.table_name='api_bil_claim_reimburse'
      AND c.column_name='bil_claim_reimburse_id' AND c.is_identity='YES'
  ) INTO is_identity;
  IF NOT is_identity THEN
    EXECUTE 'ALTER TABLE public.api_bil_claim_reimburse ALTER COLUMN bil_claim_reimburse_id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;
